language: c
sudo: required

env:
    global:
        - CC=gcc-4.8
        - FC=gfortran-4.8
        - OMPI_CC=${CC}
        - OMPI_FC=${FC}
        - PFUNIT=${PWD}/pfunit
        - PFUNIT_VERSION=3.2.7

install:
    - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install ${CC} ${FC} libgomp1 openmpi-bin libopenmpi-dev cmake

    - git clone --branch ${PFUNIT_VERSION} --depth 5 git://git.code.sf.net/p/pfunit/code pfunit-src
    - make  -C pfunit-src F90=${FC} F90_VENDOR=GNU MPI=YES INSTALL_DIR=${PFUNIT}
    - make  -C pfunit-src F90=${FC} F90_VENDOR=GNU MPI=YES INSTALL_DIR=${PFUNIT} install

script:
    - make debug
    - ctest
